blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/<pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<pk>/remove/', views.comment_remove, name='comment_remove'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', views.SignUpView.as_view(), name="signup"),
    path('accounts/login/', auth_views.login, name="login"),
    path('accounts/logout/', auth_views.logout, name='logout', kwargs={'next_page':'/'}),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse('post_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from blog.models import Comment, Post

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'password', 'email')


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('author', 'title', 'text')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'}),
        }

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('author', 'text')
        widgets = {
            'author': forms.TextInput(attrs={'class':'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from blog.models import Comment, Post
from blog.forms import PostForm, CommentForm, UserForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import (FormView, CreateView, UpdateView, DeleteView)
# Create your views here.

class SignUpView(FormView):
    form_class = UserForm
    template_name = 'signup.html'
    success_url = '/accounts/login/'

    def form_valid(self, form):
        user = form.save()
        user.set_password(user.password)
        user.save()
        return redirect(self.get_success_url())

class AboutView(TemplateView):
    template_name = 'about.html'


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    model = Post


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('post_list')


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('-create_date')



#################################################

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail', pk=post_pk)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>About page</h1>
<p>Thanks for checking out!</p>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Blog</title>
        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <!-- Medium Style Editor -->
        <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Mina|Roboto+Condensed" rel="stylesheet">

    </head>
    <body>
        <!-- NAVBAR -->
        <nav class="navbar navbar-default techfont custom-navbar">
            <div class="container">
                <ul class='nav navbar-nav'>
                    <li><a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">My blog</a></li>
                    <li><a class="navbar-link" href="{% url 'blog:about' %}">About</a></li>
                    <li><a class="navbar-link" href="https://www.github.com">GitHub</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'blog:post_new' %}">New Post</a>
                        </li>
                        <li>
                            <a href="{% url 'blog:post_draft_list' %}">Drafts</a>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}">Log Out</a>
                        </li>
                        <li>
                            <a href="#">Welcome: {{ user.username }}</a>
                        </li>
                    {% else %}
                        <li>
                            <a class="nav navbar-right" href="{% url 'signup' %}">Sign Up</a>
                        </li>
                        <li>
                            <a class="nav navbar-right" href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <!-- CONTENT BLOCK -->
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    <div class="blog_posts">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>New Comment</h1>
    <form class="post-form" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="save btn btn-default" value="Post Comment">
    </form>
    <script type="text/javascript">
        var editor = new MediumEditor('.editable');
    </script>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete {{ object }}?</p>
        <input type="submit" class="btn btn-danger" value="Yes">
    </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1 class="posttitle">{{ post.title }}</h1>
    {% if post.published_date %}
        <div class="date postdate">
            {{ post.published_date }}
        </div>
    {% else %}
        <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
    {% endif %}

    <p class="postcontent">{{ post.text|safe|linebreaksbr }}</p>

    {% if user.is_authenticated %}
        <a class="btn btn-primary" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-primary" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
    {% endif %}

    <hr>
    <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>

    <div class="container">
        {% for comment in post.comments.all %}
            <br>
            {% if user.is_authenticated or comment.approved_comment %}
                {{ comment.create_date }}
                {% if not comment.approved_comment %}
                    <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                    <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                {% endif %}
                <p>{{ comment.text|safe|linebreaksbr }}</p>
                <p>Posted By: {{ comment.author }}</p>
            {% endif %}
            {% empty %}
            <p>No Comments</p>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y'}}</p>
            <h1>
                <a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a>
            </h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>New Post</h1>
    <form class="post-form" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="save btn btn-default" value="Save">
    </form>

    <script type="text/javascript">
        var editor = new MediumEditor('.editable');
    </script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="centerstage">
    {% for post in post_list %}
    <div class="post">
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <div class="date">
            <p>Published on: {{post.create_date|date:"D M Y"}}</p>
        </div>
        <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
    </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/blog/signup.html
{% extends 'blog/base.html' %}
{% block content %}
<div class="container">
    <h1>Register Here</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-danger" value="Sign Up">
    </form>
</div>
{% endblock %}